name: Quiz Announcement

on:
  schedule:
    - cron: '0 */10 * * *' # This will run every Monday at 9 AM UTC

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
      - name: Post quiz announcement
        uses: octokit/request-action@v2
        with:
          route: POST /repos/{owner}/{repo}/discussions
          owner: ${{ secrets.OWNER }}
          repo: ${{ secrets.REPO }}
          title: 'Day 1 Quiz: Test Your Knowledge'
          body: |
            # Day 1 Quiz: Test Your Knowledge

            Hello Challenge Participants!

            It’s time for the Day 1 quiz. Please answer the questions in the Google Form linked below:

            **Quiz Link:** [Day 1 Quiz](https://forms.gle/MrhpBWuqohcsmnHy5)

            **Instructions:**
            - Click the link to access the quiz.
            - Complete the quiz and submit your answers.
            - You will see your score at the end of the quiz.

            **Deadline:**  16/08/2024

            Looking forward to your responses and discussing the answers!

            Best,
            [Your Name]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
